### ISSUE TITLE
Convert to checksum address before storing to DB

### ISSUE THREAD

**Issue by safuyield** [safuyield/safuscan-api#13]
- [ ] We want to store checksummed 0x address to avoid duplicates -> https://piyopiyo.medium.com/how-to-convert-ethereum-address-to-checksum-address-cd3e2305e2fc (Web3.utils.toChecksumAddress)
- [ ] This should avoid duplicates being stored right now like https://fomo.tech/api/info?address=0xc74cd0042c837ce59210857504ebb0859e06aa22 or https://fomo.tech/api/info?address=0xc74cD0042c837Ce59210857504eBb0859E06aA22
- [ ] If the user enters a non checksummed address, just convert it in the background

**Comment by mark0w** [comment]
Good find! Will do it asap

**Comment by mark0w** [comment]
Done. Pushed to master branch
