### ISSUE TITLE
Add a simple counter - stats per token + total

### ISSUE THREAD

**Issue by gregmeszaros** [safuyield/safuscan-api#9]
- Each time the API get request is executed 2 things should happen

- [ ] Counter for each token contract - suggest creating a new field api_stats_counter so we know each token address "popularity"
- [ ] Increase the total_api_calls field this is a simple counter for now so we can track the number of times the API was used (we will expand on this later, such as IP address, auth token or wallet address to have better/specific API access permissions

**Comment by mark0w** [comment]
Done. Now there is a new collection created called "stats" for global statistics.
